P8105 Homework 6
================
Aisha Waggeh
2025-12-02

# Problem 1

``` r
# Load and clean homicide data from GitHub
homicide_df <- read_csv(
  "https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv"
) 
glimpse(homicide_df)
```

    ## Rows: 52,179
    ## Columns: 12
    ## $ uid           <chr> "Alb-000001", "Alb-000002", "Alb-000003", "Alb-000004", …
    ## $ reported_date <dbl> 20100504, 20100216, 20100601, 20100101, 20100102, 201001…
    ## $ victim_last   <chr> "GARCIA", "MONTOYA", "SATTERFIELD", "MENDIOLA", "MULA", …
    ## $ victim_first  <chr> "JUAN", "CAMERON", "VIVIANA", "CARLOS", "VIVIAN", "GERAL…
    ## $ victim_race   <chr> "Hispanic", "Hispanic", "White", "Hispanic", "White", "W…
    ## $ victim_age    <chr> "78", "17", "15", "32", "72", "91", "52", "52", "56", "4…
    ## $ victim_sex    <chr> "Male", "Male", "Female", "Male", "Female", "Female", "M…
    ## $ city          <chr> "Albuquerque", "Albuquerque", "Albuquerque", "Albuquerqu…
    ## $ state         <chr> "NM", "NM", "NM", "NM", "NM", "NM", "NM", "NM", "NM", "N…
    ## $ lat           <dbl> 35.09579, 35.05681, 35.08609, 35.07849, 35.13036, 35.151…
    ## $ lon           <dbl> -106.5386, -106.7153, -106.6956, -106.5561, -106.5810, -…
    ## $ disposition   <chr> "Closed without arrest", "Closed by arrest", "Closed wit…

``` r
 homicide_df <- homicide_df %>%
  mutate(
    city_state = paste(city, state, sep = ", "),
    resolved = as.numeric(disposition == "Closed by arrest")
  ) %>%
  filter(!city_state %in% c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO", "Tulsa, AL")) %>%
  filter(victim_race %in% c("White", "Black")) %>%
  mutate(
    victim_age = as.numeric(victim_age),
    victim_race = fct_relevel(victim_race, "White"),
    victim_sex = fct_relevel(victim_sex, "Female")
  )

# Check structure of data
homicide_df |> 
  summarise(across(everything(), ~sum(is.na(.))))
```

    ## # A tibble: 1 × 14
    ##     uid reported_date victim_last victim_first victim_race victim_age victim_sex
    ##   <int>         <int>       <int>        <int>       <int>      <int>      <int>
    ## 1     0             0           0            0           0        290          0
    ## # ℹ 7 more variables: city <int>, state <int>, lat <int>, lon <int>,
    ## #   disposition <int>, city_state <int>, resolved <int>

``` r
# Check for missing data
homicide_df |> 
  filter(is.na(victim_age)) |> 
  count(city_state) |> 
  arrange(desc(n))
```

    ## # A tibble: 28 × 2
    ##    city_state            n
    ##    <chr>             <int>
    ##  1 Richmond, VA        107
    ##  2 Los Angeles, CA      26
    ##  3 Detroit, MI          17
    ##  4 New Orleans, LA      14
    ##  5 Charlotte, NC        13
    ##  6 Houston, TX          12
    ##  7 Oklahoma City, OK    12
    ##  8 Tampa, FL             9
    ##  9 Birmingham, AL        8
    ## 10 Miami, FL             8
    ## # ℹ 18 more rows

``` r
# Handling missing values
homicide_df = homicide_df |> 
  drop_na(victim_age) 

# Verify clean data
homicide_df |> 
  summarise(n = n(), missing_age = sum(is.na(victim_age)))
```

    ## # A tibble: 1 × 2
    ##       n missing_age
    ##   <int>       <int>
    ## 1 39403           0

``` r
# Baltimore analysis first
baltimore_df = 
  homicide_df |> 
  filter(city_state == "Baltimore, MD")

# Fit logistic regression model
fit_logistic = 
  baltimore_df |> 
  glm(resolved ~ victim_age + victim_sex + victim_race, 
      data = _, 
      family = binomial())

# Results 
baltimore_results = 
  fit_logistic |> 
  broom::tidy() |> 
  mutate(OR = exp(estimate)) |> 
  filter(term == "victim_sexMale") |> 
  select(term, OR, p.value)

# Add confidence intervals 
baltimore_results_ci = 
  fit_logistic |> 
  broom::tidy(conf.int = TRUE) |> 
  filter(term == "victim_sexMale") |> 
  mutate(
    OR = exp(estimate),
    OR_CI_lower = exp(conf.low),
    OR_CI_upper = exp(conf.high)
  ) |> 
  select(term, OR, OR_CI_lower, OR_CI_upper, p.value)

baltimore_results_ci
```

    ## # A tibble: 1 × 5
    ##   term              OR OR_CI_lower OR_CI_upper  p.value
    ##   <chr>          <dbl>       <dbl>       <dbl>    <dbl>
    ## 1 victim_sexMale 0.426       0.324       0.558 6.26e-10

``` r
# Function to fit model for each city
fit_city_model = function(df) {
  fit = glm(resolved ~ victim_age + victim_sex + victim_race, 
            data = df, 
            family = binomial())
  
  broom::tidy(fit, conf.int = TRUE) %>%
    filter(term == "victim_sexMale") %>%
    mutate(
      OR = exp(estimate),
      CI_lower = exp(conf.low),
      CI_upper = exp(conf.high)
    ) %>%
    select(OR, CI_lower, CI_upper)
}

# Apply to all cities
city_results = 
  homicide_df %>%
  nest(data = -city_state) %>%
  mutate(
    model_results = map(data, fit_city_model)
  ) %>%
  select(-data) %>%
  unnest(model_results) %>%
  arrange(OR)

city_results
```

    ## # A tibble: 47 × 4
    ##    city_state         OR CI_lower CI_upper
    ##    <chr>           <dbl>    <dbl>    <dbl>
    ##  1 New York, NY    0.262    0.133    0.485
    ##  2 Baton Rouge, LA 0.381    0.204    0.684
    ##  3 Omaha, NE       0.382    0.199    0.711
    ##  4 Cincinnati, OH  0.400    0.231    0.667
    ##  5 Chicago, IL     0.410    0.336    0.501
    ##  6 Long Beach, CA  0.410    0.143    1.02 
    ##  7 San Diego, CA   0.413    0.191    0.830
    ##  8 Baltimore, MD   0.426    0.324    0.558
    ##  9 Pittsburgh, PA  0.431    0.263    0.696
    ## 10 Denver, CO      0.479    0.233    0.962
    ## # ℹ 37 more rows

``` r
# Create plot
city_plot = city_results %>%
  mutate(
    city_state = fct_reorder(city_state, OR)
  ) %>%
  ggplot(aes(x = city_state, y = OR, ymin = CI_lower, ymax = CI_upper)) +
  geom_point() +
  geom_errorbar(width = 0.2) +
  geom_hline(yintercept = 1, linetype = "dashed", color = "red") +
  coord_flip() +
  labs(
    title = "Adjusted Odds Ratios for Homicide Resolution",
    subtitle = "Male vs Female Victims (95% Confidence Intervals)",
    x = "City",
    y = "Odds Ratio"
  ) +
  theme_minimal() +
  theme(
    axis.text.y = element_text(size = 8),
    plot.title = element_text(face = "bold")
  )

city_plot
```

![](figs/unnamed-chunk-4-1.png)<!-- -->

**Interpretation of plot**

The plot shows the adjusted odds ratios (ORs) for homicide resolution
comparing male to female victims across cities. An OR below 1 indicates
that male victims are less likely to have their cases resolved compared
to female victims. Cities like New York, NY and Baton Rouge, LA have the
lowest ORs, suggesting greater disparity, while cities with ORs closer
to 1 indicate more equal resolution rates.

# Problem 2

``` r
# Load weather data
data("weather_df")

# Clean data
weather_clean = weather_df %>%
  select(tmax, tmin, prcp) %>%
  drop_na()

# Function for bootstrap statistics
bootstrap_stats = function(df) {
  boot_sample = sample_frac(df, replace = TRUE)
  
  fit = lm(tmax ~ tmin + prcp, data = boot_sample)
  
  # Extract r-squared
  r2 = broom::glance(fit)$r.squared
  
  # Extract betas and compute product
  betas = broom::tidy(fit) %>%
    filter(term %in% c("tmin", "prcp")) %>%
    pull(estimate)
  
  beta_product = if(length(betas) == 2) prod(betas) else NA
  
  tibble(r_squared = r2, beta_product = beta_product)
}

# Run bootstrap
set.seed(123)
n_boot = 5000

bootstrap_results = 
  tibble(boot_id = 1:n_boot) %>%
  mutate(
    stats = map(boot_id, ~bootstrap_stats(weather_clean))
  ) %>%
  unnest(stats)

# Calculate confidence intervals
ci_r2 = bootstrap_results %>%
  summarise(
    lower = quantile(r_squared, 0.025, na.rm = TRUE),
    upper = quantile(r_squared, 0.975, na.rm = TRUE)
  )

ci_beta = bootstrap_results %>%
  summarise(
    lower = quantile(beta_product, 0.025, na.rm = TRUE),
    upper = quantile(beta_product, 0.975, na.rm = TRUE)
  )

# Display CIs
ci_r2
```

    ## # A tibble: 1 × 2
    ##   lower upper
    ##   <dbl> <dbl>
    ## 1 0.934 0.947

``` r
ci_beta
```

    ## # A tibble: 1 × 2
    ##      lower    upper
    ##      <dbl>    <dbl>
    ## 1 -0.00821 -0.00373

``` r
# Plot distributions
plot_r2 = bootstrap_results %>%
  ggplot(aes(x = r_squared)) +
  geom_histogram(bins = 50, fill = "lightblue", alpha = 0.7) +
  geom_vline(xintercept = ci_r2$lower, linetype = "dashed", color = "red") +
  geom_vline(xintercept = ci_r2$upper, linetype = "dashed", color = "red") +
  labs(
    title = "Bootstrap Distribution of R-squared",
    x = "R-squared",
    y = "Frequency"
  ) +
  theme_minimal()

plot_beta = bootstrap_results %>%
  ggplot(aes(x = beta_product)) +
  geom_histogram(bins = 50, fill = "lightgreen", alpha = 0.7) +
  geom_vline(xintercept = ci_beta$lower, linetype = "dashed", color = "red") +
  geom_vline(xintercept = ci_beta$upper, linetype = "dashed", color = "red") +
  labs(
    title = "Bootstrap Distribution of β1 × β2",
    x = "β1 × β2",
    y = "Frequency"
  ) +
  theme_minimal()

plot_r2
```

![](figs/unnamed-chunk-6-1.png)<!-- -->

``` r
plot_beta
```

![](figs/unnamed-chunk-6-2.png)<!-- -->

**Interpretation of bootstrap distributions:**

The bootstrap distributions show the variability in R-squared and the
product of coefficients (β1 × β2) across 5000 resamples. For R-squared,
most resamples fall between 0.934 and 0.947, indicating high model fit.
For β1 × β2, the distribution is narrowly negative (-0.0082 to -0.0037),
suggesting a small negative interaction effect between tmin and prcp on
tmax in the model.

# Problem 3

``` r
# 1. Load and clean data
birthweight_data <- read_csv("data/birthweight.csv")

# Check structure and summary
glimpse(birthweight_data)
```

    ## Rows: 4,342
    ## Columns: 20
    ## $ babysex  <dbl> 2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 2, 1, 2, 1, 1, 2, 1, 2, 2, 2, 1…
    ## $ bhead    <dbl> 34, 34, 36, 34, 34, 33, 33, 33, 36, 33, 35, 35, 35, 36, 35, 3…
    ## $ blength  <dbl> 51, 48, 50, 52, 52, 52, 46, 49, 52, 50, 51, 51, 48, 53, 51, 4…
    ## $ bwt      <dbl> 3629, 3062, 3345, 3062, 3374, 3374, 2523, 2778, 3515, 3459, 3…
    ## $ delwt    <dbl> 177, 156, 148, 157, 156, 129, 126, 140, 146, 169, 130, 146, 1…
    ## $ fincome  <dbl> 35, 65, 85, 55, 5, 55, 96, 5, 85, 75, 55, 55, 75, 75, 65, 75,…
    ## $ frace    <dbl> 1, 2, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1…
    ## $ gaweeks  <dbl> 39.9, 25.9, 39.9, 40.0, 41.6, 40.7, 40.3, 37.4, 40.3, 40.7, 4…
    ## $ malform  <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
    ## $ menarche <dbl> 13, 14, 12, 14, 13, 12, 14, 12, 11, 12, 13, 12, 13, 11, 12, 1…
    ## $ mheight  <dbl> 63, 65, 64, 64, 66, 66, 72, 62, 61, 64, 67, 62, 64, 68, 62, 6…
    ## $ momage   <dbl> 36, 25, 29, 18, 20, 23, 29, 19, 13, 19, 23, 16, 28, 23, 21, 1…
    ## $ mrace    <dbl> 1, 2, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1…
    ## $ parity   <dbl> 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
    ## $ pnumlbw  <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
    ## $ pnumsga  <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
    ## $ ppbmi    <dbl> 26.27184, 21.34485, 23.56517, 21.84508, 21.02642, 18.60030, 1…
    ## $ ppwt     <dbl> 148, 128, 137, 127, 130, 115, 105, 119, 105, 145, 110, 115, 1…
    ## $ smoken   <dbl> 0.000, 0.000, 1.000, 10.000, 1.000, 0.000, 0.000, 0.000, 0.00…
    ## $ wtgain   <dbl> 29, 28, 11, 30, 26, 14, 21, 21, 41, 24, 20, 31, 23, 21, 24, 2…

``` r
summary(birthweight_data)
```

    ##     babysex          bhead          blength           bwt           delwt      
    ##  Min.   :1.000   Min.   :21.00   Min.   :20.00   Min.   : 595   Min.   : 86.0  
    ##  1st Qu.:1.000   1st Qu.:33.00   1st Qu.:48.00   1st Qu.:2807   1st Qu.:131.0  
    ##  Median :1.000   Median :34.00   Median :50.00   Median :3132   Median :143.0  
    ##  Mean   :1.486   Mean   :33.65   Mean   :49.75   Mean   :3114   Mean   :145.6  
    ##  3rd Qu.:2.000   3rd Qu.:35.00   3rd Qu.:51.00   3rd Qu.:3459   3rd Qu.:157.0  
    ##  Max.   :2.000   Max.   :41.00   Max.   :63.00   Max.   :4791   Max.   :334.0  
    ##     fincome          frace          gaweeks         malform        
    ##  Min.   : 0.00   Min.   :1.000   Min.   :17.70   Min.   :0.000000  
    ##  1st Qu.:25.00   1st Qu.:1.000   1st Qu.:38.30   1st Qu.:0.000000  
    ##  Median :35.00   Median :2.000   Median :39.90   Median :0.000000  
    ##  Mean   :44.11   Mean   :1.655   Mean   :39.43   Mean   :0.003455  
    ##  3rd Qu.:65.00   3rd Qu.:2.000   3rd Qu.:41.10   3rd Qu.:0.000000  
    ##  Max.   :96.00   Max.   :8.000   Max.   :51.30   Max.   :1.000000  
    ##     menarche        mheight          momage         mrace      
    ##  Min.   : 0.00   Min.   :48.00   Min.   :12.0   Min.   :1.000  
    ##  1st Qu.:12.00   1st Qu.:62.00   1st Qu.:18.0   1st Qu.:1.000  
    ##  Median :12.00   Median :63.00   Median :20.0   Median :2.000  
    ##  Mean   :12.51   Mean   :63.49   Mean   :20.3   Mean   :1.627  
    ##  3rd Qu.:13.00   3rd Qu.:65.00   3rd Qu.:22.0   3rd Qu.:2.000  
    ##  Max.   :19.00   Max.   :77.00   Max.   :44.0   Max.   :4.000  
    ##      parity            pnumlbw     pnumsga      ppbmi            ppwt      
    ##  Min.   :0.000000   Min.   :0   Min.   :0   Min.   :13.07   Min.   : 70.0  
    ##  1st Qu.:0.000000   1st Qu.:0   1st Qu.:0   1st Qu.:19.53   1st Qu.:110.0  
    ##  Median :0.000000   Median :0   Median :0   Median :21.03   Median :120.0  
    ##  Mean   :0.002303   Mean   :0   Mean   :0   Mean   :21.57   Mean   :123.5  
    ##  3rd Qu.:0.000000   3rd Qu.:0   3rd Qu.:0   3rd Qu.:22.91   3rd Qu.:134.0  
    ##  Max.   :6.000000   Max.   :0   Max.   :0   Max.   :46.10   Max.   :287.0  
    ##      smoken           wtgain      
    ##  Min.   : 0.000   Min.   :-46.00  
    ##  1st Qu.: 0.000   1st Qu.: 15.00  
    ##  Median : 0.000   Median : 22.00  
    ##  Mean   : 4.145   Mean   : 22.08  
    ##  3rd Qu.: 5.000   3rd Qu.: 28.00  
    ##  Max.   :60.000   Max.   : 89.00

``` r
# Check for missing values
sum(is.na(birthweight_data))
```

    ## [1] 0

``` r
# Convert categorical variables to factors
birthweight_data <- birthweight_data %>%
  mutate(
    babysex = factor(babysex, levels = c(1, 2), labels = c("male", "female")),
    frace = factor(frace),
    malform = factor(malform),
    mrace = factor(mrace)
  )

# 2. Build your model
# Based on domain knowledge and literature, I'll build a model with key predictors
# known to affect birth weight

model_fit <- lm(bwt ~ blength + gaweeks + delwt + smoken + mrace + fincome, 
                data = birthweight_data)

# Model summary
summary(model_fit)
```

    ## 
    ## Call:
    ## lm(formula = bwt ~ blength + gaweeks + delwt + smoken + mrace + 
    ##     fincome, data = birthweight_data)
    ## 
    ## Residuals:
    ##     Min      1Q  Median      3Q     Max 
    ## -1636.8  -206.5    -7.3   200.1  3731.3 
    ## 
    ## Coefficients:
    ##               Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept) -3980.7112    98.4845 -40.420  < 2e-16 ***
    ## blength       117.1473     1.9678  59.532  < 2e-16 ***
    ## gaweeks        23.0801     1.6487  13.999  < 2e-16 ***
    ## delwt           3.0135     0.2255  13.365  < 2e-16 ***
    ## smoken         -6.1425     0.6779  -9.061  < 2e-16 ***
    ## mrace2       -172.6160    11.4560 -15.068  < 2e-16 ***
    ## mrace3        -56.3389    49.1151  -1.147  0.25141    
    ## mrace4        -86.6346    21.9807  -3.941 8.23e-05 ***
    ## fincome         0.5689     0.2019   2.817  0.00487 ** 
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 316.4 on 4333 degrees of freedom
    ## Multiple R-squared:  0.6191, Adjusted R-squared:  0.6184 
    ## F-statistic: 880.3 on 8 and 4333 DF,  p-value: < 2.2e-16

``` r
# Check model diagnostics
model_fit %>%
  augment() %>%
  ggplot(aes(x = .fitted, y = .resid)) +
  geom_point(alpha = 0.5) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  labs(title = "Residuals vs Fitted Values",
       x = "Fitted Values",
       y = "Residuals")
```

![](figs/unnamed-chunk-7-1.png)<!-- -->

``` r
# QQ plot for normality
model_fit %>%
  augment() %>%
  ggplot(aes(sample = .std.resid)) +
  geom_qq() +
  geom_qq_line() +
  labs(title = "Normal Q-Q Plot")
```

![](figs/unnamed-chunk-7-2.png)<!-- -->

``` r
# 3. Compare with two other models
# Model 1: Length at birth and gestational age (from problem 1)
model1 <- lm(bwt ~ blength + gaweeks, data = birthweight_data)

# Model 2: Head circumference, length, sex, and all interactions (from problem 2)
model2 <- lm(bwt ~ bhead + blength + babysex + 
               bhead*blength + bhead*babysex + blength*babysex + 
               bhead*blength*babysex, 
             data = birthweight_data)

# 4. Cross-validation to compare models
set.seed(123)  # For reproducibility

cv_df <- crossv_mc(birthweight_data, 100) %>%
  mutate(
    # Your model
    train_model = map(train, ~lm(bwt ~ blength + gaweeks + delwt + smoken + mrace + fincome, data = .)),
    
    # Model 1
    train_model1 = map(train, ~lm(bwt ~ blength + gaweeks, data = .)),
    
    # Model 2
    train_model2 = map(train, ~lm(bwt ~ bhead + blength + babysex + 
                                    bhead*blength + bhead*babysex + blength*babysex + 
                                    bhead*blength*babysex, data = .)),
    
    # Calculate RMSE for each model
    rmse_model = map2_dbl(train_model, test, ~rmse(model = .x, data = .y)),
    rmse_model1 = map2_dbl(train_model1, test, ~rmse(model = .x, data = .y)),
    rmse_model2 = map2_dbl(train_model2, test, ~rmse(model = .x, data = .y))
  )

# Compare RMSE distribution
cv_df %>%
  select(starts_with("rmse")) %>%
  pivot_longer(
    everything(),
    names_to = "model", 
    values_to = "rmse",
    names_prefix = "rmse_"
  ) %>%
  mutate(model = fct_recode(model,
                            "My Model" = "model",
                            "Length + Gestation" = "model1",
                            "Head Circ + Length + Sex + Interactions" = "model2")) %>%
  ggplot(aes(x = model, y = rmse, fill = model)) +
  geom_violin() +
  labs(title = "Model Comparison using Cross-Validated RMSE",
       x = "Model",
       y = "Root Mean Square Error (RMSE)") +
  theme_minimal() +
  theme(legend.position = "none")
```

![](figs/unnamed-chunk-7-3.png)<!-- -->

``` r
# 5. Plot of model residuals vs fitted values for your model
birthweight_data %>%
  add_residuals(model_fit) %>%
  add_predictions(model_fit) %>%
  ggplot(aes(x = pred, y = resid)) +
  geom_point(alpha = 0.3) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  labs(title = "Residuals vs Fitted Values (My Model)",
       x = "Fitted Values",
       y = "Residuals") +
  theme_minimal()
```

![](figs/unnamed-chunk-7-4.png)<!-- -->

``` r
# cross-validation plot for futher justification:
cv_summary <- cv_df %>%
  select(starts_with("rmse")) %>%
  pivot_longer(everything(), names_to = "model", values_to = "rmse") %>%
  group_by(model) %>%
  summarise(
    mean_rmse = mean(rmse),
    sd_rmse = sd(rmse),
    ci_lower = quantile(rmse, 0.025),
    ci_upper = quantile(rmse, 0.975)
  )

cv_summary
```

    ## # A tibble: 3 × 5
    ##   model       mean_rmse sd_rmse ci_lower ci_upper
    ##   <chr>           <dbl>   <dbl>    <dbl>    <dbl>
    ## 1 rmse_model       314.   11.3      299.     341.
    ## 2 rmse_model1      331.   12.6      312.     363.
    ## 3 rmse_model2      288.    8.24     273.     306.

**Justification for model choice:**

My model (blength + gaweeks + delwt + smoken + mrace + fincome) achieves
a cross-validated RMSE of 314.5 (95% CI: 299-341), representing a
meaningful 16.2-point improvement over the simple length+gestation model
(RMSE = 330.7, 95% CI: 312-363). This 4.9% reduction in prediction error
demonstrates that including maternal factors—delivery weight, smoking
status, race, and family income—adds substantial predictive value beyond
basic biometric measures alone.

While the complex interaction model with head circumference, length,
sex, and all three-way interactions achieves the lowest RMSE at 288.4
(95% CI: 273-306), my model offers important practical advantages:

1.  **Clinical interpretability**: Each predictor in my model has a
    clear, evidence-based relationship with birthweight documented in
    the epidemiological literature. In contrast, the three-way
    interaction in Model 2, while statistically significant, is
    challenging to explain in clinical or public health terms and may
    represent overfitting to noise in the data.

2.  **Actionable insights**: The factors in my model, particularly
    smoking cessation (smoken), maternal nutrition (proxied by delwt),
    and socioeconomic status (fincome) are potentially modifiable
    through interventions. This makes the model directly applicable for
    developing targeted clinical counseling or public health strategies.

3.  **Optimal complexity**: My model uses 6 main effects (plus factor
    levels for mrace), compared to Model 2’s 15 parameters including
    complex interactions. The narrower confidence interval for Model 2’s
    RMSE (8.2 vs 11.3-12.6 for the other models) suggests it may be more
    sensitive to specific data patterns, potentially reducing
    generalizability.

4.  **Performance tradeoff analysis**: The performance hierarchy shows
    my model captures approximately 84% of the predictive improvement
    from Model 1 to Model 2 \[(330.7-314.5)/(330.7-288.4) = 0.84\] while
    using only 53% as many parameters as Model 2 (8 vs 15). This
    represents an excellent efficiency gain in terms of predictive power
    per parameter.

For applications where understanding the mechanistic drivers of
birthweight is as important as prediction accuracy such as clinical risk
assessment, public health program design, or etiological research, my
model represents an optimal choice. It balances biological plausibility,
clinical interpretability, and robust predictive performance while
avoiding the potential overfitting risks of highly complex interaction
models.
